### ISSUE TITLE
this one has an attachment, can you see it?

### ISSUE THREAD

**Issue by rivques** [hheisig51/BankCarton#16]
3d print please (not really this is a test)
[filament-clip-model_files.zip](https://github.com/hheisig51/BankCarton/files/9436160/grandmas-favorite-filament-clip-model_files.zip)
github doesn't support stls so you have to wrap them in a .zip

pulled [a model off of printables](https://www.printables.com/model/24371-grandmas-favorite-filament-clip)

**Comment by hheisig51** [comment]
good use case. I was thinking 3d printing could be implemented in 4 different ways
- Exactly like this.
- Through a different repo, so it doesn't clutter up the actual issues.
- Through any native queue/approval system the printers/network may have already.
- Through Github's "projects" system.

**Comment by rivques** [comment]
looks like you have to parse the body for links, then see if any of those are files hosted by github (url looks like `REPO_URL/files/RANDOM_FILE_ID/FILE_NAME`). Don't have enough time to do that right now and not sure if it's worth doing.

**Comment by hheisig51** [comment]
Yep. I've experienced that before with github's storing of files. Brought me a lot of pain when I was trying to embed videos into my README.

Anyways, next chance I get, I'm going to explore other solutions for a print queue. Onshape has to have something!

**Comment by rivques** [comment]
Yeah, I'm not sure GitHub is the correct platform for this given that STLs are not supported. It would be nice (but maybe more trouble than it's worth) to integrate slicers better into the workflow, especially grabCAD where there's not many knobs to turn. No matter what, I think we can do better than the Print Me folder.

**Comment by rivques** [comment]
The other party in that conversation may have been me, though I think grabCAD does have its place. In my opinion the biggest issue with the print me folder (besides how cluttered it gets) is that there's no good way to specify information about how you want the file printed; it's not particularly convenient to name a file `part (x4) high infill print with long axis horizontal.stl`. Someone else has almost certainly had this issue before and made a solution, the challenge is likely to be finding a solution that doesn't require new accounts, is free, and doesn't require too much work to integrate with our current workflows.
